%YAML:1.0
---
Robot:
   baseLinkPosCoord: [ 0., 0. ]
   numAngleStep: 360
   testpoints: !!opencv-matrix
      rows: 5
      cols: 3
      dt: f
      data: [0.574, 0.252, 0.1,   0.574, -0.252, 0.1,   0., 0.29, 0.1,   0., -0.29, 0.1,   0.287, 0., 0.3]
