name: publish_docker

on:
  push: []
  schedule:
    # build every night at 0:00
    - cron:  '0 0 * * *'

jobs:
  build-docker-18-melodic:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
      with:
        path: src/gerona
    - uses: actions/checkout@v2
      with:
        repository: cogsys-tuebingen/cslibs_path_planning
        path: src/cslibs_path_planning
    - uses: actions/checkout@v2
      with:
        repository: cogsys-tuebingen/cslibs_navigation_utilities
        path: src/cslibs_navigation_utilities
    - uses: actions/checkout@v2
      with:
        repository: sbpl/sbpl
        path: src/sbpl
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: cogsys-tuebingen/gerona/gerona_melodic
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: src/gerona/docker/melodic-perception.docker

  build-docker-20-noetic:
    runs-on: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
      with:
        path: src/gerona
    - uses: actions/checkout@v2
      with:
        repository: cogsys-tuebingen/cslibs_path_planning
        path: src/cslibs_path_planning
    - uses: actions/checkout@v2
      with:
        repository: cogsys-tuebingen/cslibs_navigation_utilities
        path: src/cslibs_navigation_utilities
    - uses: actions/checkout@v2
      with:
        repository: sbpl/sbpl
        path: src/sbpl
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: cogsys-tuebingen/gerona/gerona_noetic
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: src/gerona/docker/noetic-perception.docker